/**
 **************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 **************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 **************************
 */

#if !defined(_SOFT_FP) && defined(_ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_GPIO_Driver.h"
#include "stm32f103x6.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "Stm32_F103C6_USART_Driver.h"


void clock_init()
{
	//Enable clock GPIOA
	RCC_GPIOA_CLK_EN() ;

	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN() ;

	//Enable clock AFIO
	AFIO_GPIOE_CLK_EN() ;


}


void wait (int x)
{
	unsigned int i , j ;
	for (i= 0 ; i<x ; i++)
		for (j= 0 ; j<255 ; j++);
}

int main(void)
{

	unsigned char ch ;
	clock_init();

	USART_Config_t UART_Cfg ;

	UART_Cfg.BaudRate = UART_BaudRate_115200 ;
	UART_Cfg.HwFlowCtl = UART_HWFlowCtrl_NONE ;
	UART_Cfg.IRQ_Enable = UART_IRQ_Enable_NONE ;
	UART_Cfg.Parity = UART_Parity_NONE ;
	UART_Cfg.Payload_Length = UART_Payload_Length_8B ;
	UART_Cfg.StopBits = UART_StopBits_1 ;
	UART_Cfg.USART_Mode = UAERT_Mode_TX_RX ;

	MCAL_UART_Init(USART1, &UART_Cfg);
	MCAL_UART_GPIO_Set_Pins(USART1);

	while (1)
	{
      MCAL_UART_SendData(USART1,&ch, enable);
      MCAL_UART_ReceiveData(USART1,&ch, enable);

	}

}
