/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "stm32f103x6.h"



unsigned int IRQ_Flag = 0 ;

enum CPUAccessLevel
{
	privileged,
	unprivileged
};

void SWITCH_CPU_AccessLevel(enum CPUAccessLevel level)
{
	switch (level)
	{
	case privileged :

		__asm("mrs r3,CONTROL   \n\t"
				"lsr r3,r3,#0x1 \n\t"
				"lsl r3,r3,#0x1 \n\t"
				"msr CONTROL,r3");
		break;

	case unprivileged :

		__asm("mrs r3,CONTROL   \n\t"
				"orr r3,r3,#0x1 \n\t"
				"msr CONTROL,r3");

		break;
	}
}


void clock_init()
{

	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN() ;

	//Enable clock AFIO
	AFIO_GPIOE_CLK_EN() ;

}

void wait (int x)
{
	unsigned int i , j ;
	for (i= 0 ; i<x ; i++)
		for (j= 0 ; j<255 ; j++);
}

void EXTI9_CallBack(void)
{
	IRQ_Flag = 1 ;

	//Handler mode >> change to privileged
	SWITCH_CPU_AccessLevel(privileged);

}




int main(void)
{
	clock_init();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9 ;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING ;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_CallBack ;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable ;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	IRQ_Flag = 1 ;

	//thread mode >> change to unprivileged
	SWITCH_CPU_AccessLevel(unprivileged);

	while (1)
	{

		if (IRQ_Flag)
		{
			IRQ_Flag = 0 ;
		}

	}



}
