/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "stm32f103x6.h"
#include "core_cm3.h"

#define TaskA_Stack_Size 100 //100 Byte
#define TaskB_Stack_Size 100 //100 Byte

extern int _estack ;

//Main  Stack
unsigned int _S_MSP = & _estack;
unsigned int _E_MSP ;

//Process Stack Task A
unsigned int _S_PSP_TA ;
unsigned int _E_PSP_TA ;

//Process Stack Task B
unsigned int _S_PSP_TB ;
unsigned int _E_PSP_TB ;

#define OS_SET_PSP(add)                      __asm volatile ("mov r0,%0 \n\t  msr PSP,r0" : : "r" (add) )
#define OS_SWITCH_SP_TO_PSP                  __asm volatile ("mrs r0,CONTROL \n\t mov r1,#0x02 \n\t orr r0,r0,r1 \n\t msr CONTROL,r0" )
#define OS_SWITCH_SP_TO_MSP                  __asm volatile ("mrs r0,CONTROL \n\t mov r1,#0x05 \n\t and r0,r0,r1 \n\t msr CONTROL,r0" )

#define OS_GENERATE_EXCEPTION                __asm volatile ("SVC #0x3")

#define SWITCH_CPU_AccessLevel_PRIVILEGED    __asm("mrs r3,CONTROL \n\t lsr r3,r3,#0x1 \n\t lsl r3,r3,#0x1 \n\t msr CONTROL,r3")
#define SWITCH_CPU_AccessLevel_UNPRIVILEGED  __asm("mrs r3,CONTROL  \n\t orr r3,r3,#0x1 \n\t msr CONTROL,r3")


unsigned int TaskA_Flag = 0 , TaskB_Flag = 0 , IRQ_Flag = 0 ;


enum CPUAccessLevel
{
	privileged,
	unprivileged
};




void SWITCH_CPU_AccessLevel(enum CPUAccessLevel level)
{
	switch (level)
	{
	case privileged :

		__asm("mrs r3,CONTROL   \n\t"
				"lsr r3,r3,#0x1 \n\t"
				"lsl r3,r3,#0x1 \n\t"
				"msr CONTROL,r3");
		break;

	case unprivileged :

		__asm("mrs r3,CONTROL   \n\t"
				"orr r3,r3,#0x1 \n\t"
				"msr CONTROL,r3");

		break;
	}
}



void clock_init()
{

	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN() ;

	//Enable clock AFIO
	AFIO_GPIO_CLK_EN();

}

void wait (int x)
{
	unsigned int i , j ;
	for (i= 0 ; i<x ; i++)
		for (j= 0 ; j<255 ; j++);
}

void EXTI9_CallBack(void)
{
	if (IRQ_Flag == 0 )
	{
		TaskA_Flag = 1 ;
		IRQ_Flag = 1 ;
	}
	else if (IRQ_Flag == 1)
	{
		TaskB_Flag = 1 ;
		IRQ_Flag = 0 ;
	}


}

int TaskA(int a,int b,int c)
{

	return a+b+c ;
}

int TaskB(int a,int b,int c,int d)
{

	return a+b+c ;
}

void MainOs()
{
	//Main Stack
	_E_MSP = (_S_MSP - 512 ) ;

	//Task A
	_S_PSP_TA = (_E_MSP - 8);
	_E_PSP_TA = (_S_PSP_TA - TaskA_Stack_Size) ;

	//Task B
	_S_PSP_TB = (_E_PSP_TA - 8);
	_E_PSP_TB = (_S_PSP_TB - TaskB_Stack_Size) ;


	while(1)
	{
		__asm("NOP");

		if (TaskA_Flag == 1)
		{
			//Set PSP Register = _s_PSP_TA
			OS_SET_PSP(_S_PSP_TA);
			//SP -> PSP
			OS_SWITCH_SP_TO_PSP;
			//Switch From Privileged to Unprivileged
			SWITCH_CPU_AccessLevel_UNPRIVILEGED;

			TaskA_Flag = TaskA(1, 2, 3);

			//Switch From Unprivileged to Privileged
			OS_GENERATE_EXCEPTION;
			//SP -> MSP
			OS_SWITCH_SP_TO_MSP;
		}
		else if (TaskB_Flag == 1 )
		{
			//Set PSP Register = _s_PSP_TB
			OS_SET_PSP(_S_PSP_TB);
			//SP -> PSP
			OS_SWITCH_SP_TO_PSP;
			//Switch From Privileged to Unprivileged
			SWITCH_CPU_AccessLevel_UNPRIVILEGED;

			TaskB_Flag = TaskB(1, 2, 3,4);

			//Switch From Unprivileged to Privileged
			OS_GENERATE_EXCEPTION;
			//SP -> MSP
			OS_SWITCH_SP_TO_MSP;
		}
	}
}

void PendSV_Handler()
{
    //PendSV_HandlerB
}

void OS_SVC_Services(int* StackFramePointer)
{
	//OS_SVC_Set stack start found in -> r0 , r0 is pointed by StackFramePointer
	//OS_SVC_Set stack : r0,r1,r2,r12,LR,PC,XPSR

	unsigned char SVC_number ;
	unsigned val1,val2 ;

	SVC_number = *((unsigned char*)(((unsigned char*)StackFramePointer[6])-2)) ;
	val1 = StackFramePointer[0];
	val2 = StackFramePointer[1];
	switch(SVC_number)
	{
	case 1 : //add
		StackFramePointer[0] = val1+val2 ;
		break;

	case 2 : //sub
		StackFramePointer[0] = val1-val2 ;
		break;

	case 3 : //mult
		StackFramePointer[0] = val1 * val2 ;
		break;

	case 4 : //OS PendSV
		SCB->ICSR |= SCB_ICSR_PENDSVSET_Msk ;
		break;
	}

}


__attribute ((naked)) void SVC_Handler()
{
	__asm("tst lr,#4       \n\t"
			"ITE EQ        \n\t"
			"mrseq r0,MSP  \n\t"
			"mrsne r0,MSP  \n\t"
			"B OS_SVC_Services");
}


int OS_SVC_Set(int a,int b, int SVC_ID)
{
	int result ;

	switch(SVC_ID)
	{
	case 1 : //add
		__asm("svc #0x01");
		break;

	case 2 : //sub
		__asm("svc #0x02");
		break;

	case 3 : //mult
		__asm("svc #0x03");
		break;

	case 4 : //mult
		__asm("svc #0x04");
		break;
	}

	__asm("mov %0,r0 \n\t"
			: "=r" (result) );
	return result ;

}

int main(void)
{


//	clock_init();
//
//	EXTI_PinConfig_t EXTI_CFG;
//	EXTI_CFG.EXTI_PIN = EXTI9PB9 ;
//	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING ;
//	EXTI_CFG.P_IRQ_CallBack = EXTI9_CallBack ;
//	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable ;
//
//	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
//
//
//	MainOs();

	while (1)
	{

	IRQ_Flag = OS_SVC_Set(3,3,1); //add
	IRQ_Flag = OS_SVC_Set(3,3,2); //sub
	IRQ_Flag = OS_SVC_Set(3,3,3); //mult


	OS_SVC_Set(0,0,4); //PendSV Call
		if (IRQ_Flag)
		{
			IRQ_Flag = 0 ;
		}

	}



}
